name: Whistless
version: 1.1
author: UselessMnemonic
description: Introduces magic whistles into the game.
website: https://github.com/UselessMnemonic

main: me.uselessmnemonic.whistles.Whistles
depend: [Slimefun]
load: POSTWORLD

api-version: 1.16